import Head from "next/head";

import styles from "../styles/Home.module.css";
import blog_main_img from "../public/img/blog_main_img.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keyword"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <img className={styles.main_img} src={blog_main_img.src} />
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Latests Blogs </h2>
          <div className="blogsItem">
            <h3>How to learn Javascript </h3>
            <p>Javascript is the language used to design for the web</p>
          </div>
          <div className="blogsItem">
            <h3>How to learn Javascript </h3>
            <p>Javascript is the language used to design for the web</p>
          </div>
          <div className="blogsItem">
            <h3>How to learn Javascript </h3>
            <p>Javascript is the language used to design for the web</p>
          </div>
          <div className="blogsItem">
            <h3>How to learn Javascript </h3>
            <p>Javascript is the language used to design for the web</p>
          </div>
        </div>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
